### ISSUE TITLE
Feedback with a 2009 iMac

### ISSUE THREAD

**Issue by berdal84** [CedricGuillemet/bam#6]
Hi, a small resume of my "clone/compile/run" test.

My config is the following:

```
Model Name:	iMac
Model Identifier: iMac11,2
Processor Name:	Intel Core i3
Processor Speed: 3.06 GHz
Number of Processors:	1
Total Number of Cores:	2
L2 Cache (per Core):	256 KB
L3 Cache:	4 MB
Memory:	16 GB
Graphics: ATI Radeon HD 4670 256 MB.   (yes, I know...)
Drive: SSD 1To
```

I was using CLion 2019.3 to generate a Makefile and to build.

For target `App` in `Debug` it took me ~15 min to compile. The log is attached.

[macos-build-debug-log.txt](https://github.com/CedricGuillemet/bam/files/8104849/macos-build-debug-log.txt)

The errors are probably due to my old system. I can't compile above C++11 for example.

**Comment by CedricGuillemet** [comment]
Yep! looks like it's a bit old and it doesn't support Metal. It's possible to disable Metal and only use OpenGL.
